In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("job_lists_export.csv" , delimiter= ";")  # Read in the job listings CSV file
df.head(1)

,id,title,user_id,location,date_posted,description,skills,min_salary,max_salary,salary_negotiable,payment_period,payment_currency,hiring_multiple_candidates
0,1,"Application Developer - ERP, Commercial CPS",12287,"Atlanta, GA, US",2025-04-15,Cargill’s size scale allows us make positive i...,"acceptance testing,application,application sup...",71538,91833,1,monthly,USD,0

In [3]:
df["full_text"] = df["title"] + ",job_description:" + df["description"]
df.head(1)

,id,title,user_id,location,date_posted,description,skills,min_salary,max_salary,salary_negotiable,payment_period,payment_currency,hiring_multiple_candidates,full_text
0,1,"Application Developer - ERP, Commercial CPS",12287,"Atlanta, GA, US",2025-04-15,Cargill’s size scale allows us make positive i...,"acceptance testing,application,application sup...",71538,91833,1,monthly,USD,0,"Application Developer - ERP, Commercial CPS,jo..."

In [4]:
from sentence_transformers import SentenceTransformer , util
model = SentenceTransformer('./job_embeddings_model_evaluated2')

d:\anaconda\envs\REC\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [5]:
job_embeddings2 = model.encode(df['full_text'].tolist(), show_progress_bar=True)

Batches: 100%|██████████| 590/590 [04:43<00:00,  2.08it/s]

In [6]:
import pickle

# Save embeddings
with open('job_embeddings.pkl', 'wb') as f:
    pickle.dump(job_embeddings2, f)
print("Embeddings saved to job_embeddings.pkl")

Embeddings saved to job_embeddings.pkl

In [7]:
with open('job_embeddings.pkl', 'rb') as f:
    loaded_embeddings = pickle.load(f)
print("Embeddings loaded from job_embeddings.pkl")

Embeddings loaded from job_embeddings.pkl