In [41]:
import PyPDF2

In [42]:
path = "Ahmed_El-Sayed_CV.pdf"

In [44]:
data = PyPDF2.PdfReader(path)
data

In [ ]:
filehandle = open("Ahmed_El-Sayed_CV.txt", "w")

In [39]:
pdfreader = PyPDF2.PdfReader(path)
text3 = ""
for page in pdfreader.pages:
    text2 = page.extract_text()
    text2 = text.replace("\n" , " ")
    text2 = text.replace("|" , " ")
    text3 += text2 + " "

In [40]:
text3

'Backend Developer CodeBaseX - Remote (Europe-based clients)   Feb 2018 – Apr 2021 - Built and maintained microservices for e-commerce and HR platforms. - Integrated third-party services including Stripe, Twilio, SendGrid, and Firebase. - Implemented role-based access control (RBAC) and OAuth authentication. - Wrote unit and feature tests using PHPUnit and Laravel Dusk. Junior Backend Developer NileSoft - Cairo, Egypt   Jul 2015 – Jan 2018 - Developed admin panels and internal tools using Laravel and Bootstrap. - Assisted in database schema design and optimization. - Participated in API documentation and Postman collection setups. Education Bachelor of Computer Science Cairo University, Egypt Graduated: 2015 Certifications Laravel Certified Developer – Laravel Certification Program (2022) AWS Certified Developer – Associate (2023) Projects - Invoicy – Invoicing SaaS platform with subscription management, built in Laravel + Vue.js - TrackWize – Employee attendance & productivity monitoring system - EduFlow – Custom LMS backend with multi-tenant support and real-time notifications Languages Arabic – Native English – Fluent Backend Developer CodeBaseX - Remote (Europe-based clients)   Feb 2018 – Apr 2021 - Built and maintained microservices for e-commerce and HR platforms. - Integrated third-party services including Stripe, Twilio, SendGrid, and Firebase. - Implemented role-based access control (RBAC) and OAuth authentication. - Wrote unit and feature tests using PHPUnit and Laravel Dusk. Junior Backend Developer NileSoft - Cairo, Egypt   Jul 2015 – Jan 2018 - Developed admin panels and internal tools using Laravel and Bootstrap. - Assisted in database schema design and optimization. - Participated in API documentation and Postman collection setups. Education Bachelor of Computer Science Cairo University, Egypt Graduated: 2015 Certifications Laravel Certified Developer – Laravel Certification Program (2022) AWS Certified Developer – Associate (2023) Projects - Invoicy – Invoicing SaaS platform with subscription management, built in Laravel + Vue.js - TrackWize – Employee attendance & productivity monitoring system - EduFlow – Custom LMS backend with multi-tenant support and real-time notifications Languages Arabic – Native English – Fluent '

In [37]:
len(text3)

2276

In [45]:
file_path = "Ahmed_El-Sayed_CV.txt"
with open(file_path, "r", encoding="utf-8") as file:
        resume_text = file.read()
resume_text

''

In [88]:
import PyPDF2
pdf_path = "Ahmed_El-Sayed_CV.pdf"
pdf_reader = PyPDF2.PdfReader(pdf_path)
resume_text = ""
for page in pdf_reader.pages:
    page_text = page.extract_text()
    # Clean up text - remove line breaks and pipes
    page_text = page_text.replace("\n", " ").replace("|", " ")
    resume_text += page_text + " "
resume_text = " ".join(resume_text.split())
resume_text

'Ahmed El-Sayed Email: ahmed.elsayed.dev@gmail.com Phone: +20 102 345 6789 Location: Cairo, Egypt LinkedIn: linkedin.com/in/ahmed-elsayed-dev GitHub: github.com/ahmed-elsayed-dev Portfolio: ahmed-elsayed.dev Professional Summary Senior Backend Developer with 8+ years of experience in designing, developing, and maintaining scalable backend systems using PHP and Laravel. Expert in RESTful APIs, microservices architecture, queue workers, database optimization, and system security. Passionate about clean code, performance optimization, and building robust systems for enterprise and SaaS applications. Technical Skills Languages: PHP, JavaScript, TypeScript, Bash Frameworks: Laravel, Lumen, Symfony (basic), Node.js (basic) Databases: MySQL, PostgreSQL, MongoDB, Redis DevOps: Docker, Nginx, GitLab CI/CD, AWS EC2, S3, CloudWatch Tools: Git, Composer, PHPUnit, Laravel Octane, Horizon, Nova API: REST, GraphQL, Passport, Sanctum Other: Microservices, Queues, Caching, Multi-tenancy, SaaS architecture Work Experience Senior Backend Developer TechHive Solutions - Cairo, Egypt May 2021 – Present - Led the backend architecture for a multi-tenant SaaS platform used by over 50,000 active users. - Designed and implemented scalable APIs using Laravel 9, Laravel Octane, and MySQL. - Refactored legacy codebase to improve performance by 45% and reduce tech debt. - Introduced Laravel Horizon for managing and monitoring queues. - Collaborated with frontend (Vue.js) and DevOps teams for full-cycle development. Backend Developer CodeBaseX - Remote (Europe-based clients) Feb 2018 – Apr 2021 - Built and maintained microservices for e-commerce and HR platforms. - Integrated third-party services including Stripe, Twilio, SendGrid, and Firebase. - Implemented role-based access control (RBAC) and OAuth authentication. - Wrote unit and feature tests using PHPUnit and Laravel Dusk. Junior Backend Developer NileSoft - Cairo, Egypt Jul 2015 – Jan 2018 - Developed admin panels and internal tools using Laravel and Bootstrap. - Assisted in database schema design and optimization. - Participated in API documentation and Postman collection setups. Education Bachelor of Computer Science Cairo University, Egypt Graduated: 2015 Certifications Laravel Certified Developer – Laravel Certification Program (2022) AWS Certified Developer – Associate (2023) Projects - Invoicy – Invoicing SaaS platform with subscription management, built in Laravel + Vue.js - TrackWize – Employee attendance & productivity monitoring system - EduFlow – Custom LMS backend with multi-tenant support and real-time notifications Languages Arabic – Native English – Fluent'

In [89]:
import pandas as pd
import re
import string
import spacy
from spacy.lang.en.stop_words import STOP_WORDS

def clean_resume_text(text):
    """Clean resume text for embedding and recommendation"""
    
    # Load spaCy model
    nlp = spacy.load('en_core_web_sm')
    
    # 1. Convert to lowercase
    text = text.lower()
    
    # 2. Remove contact information
    text = re.sub(r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b', ' ', text)  # Email
    text = re.sub(r'(\+\d{1,3}[-\s]?)?\(?\d{3}\)?[-\s]?\d{3}[-\s]?\d{4}', ' ', text)  # Phone
    
    # 3. Remove URLs and social media handles
    text = re.sub(r'https?://\S+|www\.\S+', ' ', text)
    text = re.sub(r'linkedin\.com\S*|github\.com\S*|twitter\.com\S*', ' ', text)
    
    # 4. Remove locations and addresses
    location_patterns = [
        r'\b[A-Z][a-z]+,\s*[A-Z]{2}\b',  # City, State
        r'\b[A-Z][a-z]+\s+[A-Z]{2}\s+\d{5}\b',  # City State ZIP
    ]
    for pattern in location_patterns:
        text = re.sub(pattern, ' ', text)
    
    # 5. Remove dates (but preserve skill versions like 'Python 3')
    text = re.sub(r'\b(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*\s+\d{4}\b', ' ', text)
    text = re.sub(r'\b\d{1,2}/\d{1,2}/\d{2,4}\b', ' ', text)
    text = re.sub(r'\b\d{4}-\d{2,4}\b', ' ', text)
    
    # 6. Remove special characters but keep important ones for skills
    text = text.replace('|', ' ').replace('•', ' ').replace('–', ' ').replace('/', ' ')
    
    # 7. Process with spaCy for advanced cleaning
    doc = nlp(text)
    
    # 8. Keep only relevant tokens 
    tokens = []
    for token in doc:
        # Skip if token is punctuation, stopword, or just whitespace
        if (
            not token.is_punct
            and not token.is_stop
            and not token.is_space
            and token.text.strip()
            and len(token.text.strip()) > 1
        ):
            # Lemmatize the token
            tokens.append(token.text)
    
    # 9. Join tokens back into cleaned text
    cleaned_text = " ".join(tokens)
    
    # 10. Remove extra whitespace
    cleaned_text = " ".join(cleaned_text.split())
    # return the cleaned_text in the shape of pandas dataframe with each has its own index
    return cleaned_text

# Example usage

In [90]:
cleaned_resume1 = clean_resume_text(resume_text)
cleaned_resume1

'ahmed el sayed email phone location cairo egypt linkedin github portfolio ahmed-elsayed.dev professional summary senior backend developer years experience designing developing maintaining scalable backend systems php laravel expert restful apis microservices architecture queue workers database optimization system security passionate clean code performance optimization building robust systems enterprise saas applications technical skills languages php javascript typescript bash frameworks laravel lumen symfony basic node.js basic databases mysql postgresql mongodb redis devops docker nginx gitlab ci cd aws ec2 s3 cloudwatch tools git composer phpunit laravel octane horizon nova api rest graphql passport sanctum microservices queues caching multi tenancy saas architecture work experience senior backend developer techhive solutions cairo egypt present led backend architecture multi tenant saas platform 50,000 active users designed implemented scalable apis laravel laravel octane mysql refactored legacy codebase improve performance 45 reduce tech debt introduced laravel horizon managing monitoring queues collaborated frontend vue.js devops teams cycle development backend developer codebasex remote europe based clients built maintained microservices commerce hr platforms integrated party services including stripe twilio sendgrid firebase implemented role based access control rbac oauth authentication wrote unit feature tests phpunit laravel dusk junior backend developer nilesoft cairo egypt developed admin panels internal tools laravel bootstrap assisted database schema design optimization participated api documentation postman collection setups education bachelor computer science cairo university egypt graduated 2015 certifications laravel certified developer laravel certification program 2022 aws certified developer associate 2023 projects invoicy invoicing saas platform subscription management built laravel vue.js trackwize employee attendance productivity monitoring system eduflow custom lms backend multi tenant support real time notifications languages arabic native english fluent'

In [91]:
import PyPDF2
pdf_path = "Ahmed-Wael-Mujahid-resume.pdf"
pdf_reader = PyPDF2.PdfReader(pdf_path)
resume_text = ""
for page in pdf_reader.pages:
    page_text = page.extract_text()
    # Clean up text - remove line breaks and pipes
    page_text = page_text.replace("\n", " ").replace("|", " ")
    resume_text += page_text + " "
resume_text2 = " ".join(resume_text.split())
resume_text2

'Ahm ed Wael Mujahid 01212808698 a7med-wael a7medwael10 Mansoura, Egypt ahmed.wael1025@gmail.com PROFILE Back-end developer specializing in PHP, Laravel, and MySQL, with a passion for building scalable and secure web applications. Experienced in RESTful API development, database optimization, and authentication systems. Always eager to learn new technologies and improve performance. EDUCATION Bachelor of Com puter and Control System s Engineering Faculty Of Engineering, Mansoura University2020 – 2025 PROFESSIONAL EXPERIENCE PHP Web Developer Digital Egypt Pioneers Initiative - DEPI · Internship04/2024 – 10/2024 •Gained hands-on experience in PHP, Laravel, and MySQL while developing web applications. •Worked on backend developm ent, database optim ization, and API integration to enhance system. •Enhanced business com m unication skills through Berlitz Egypt (Business English Track). •Led the development team in building the backend of "Fork & Knife", a restaurant management system. PROJECTS Fadfadly – AI-Powered Mental Health Platform Developed the backend RESTful APIs using Laravel & MySQL, implementing: •Custom AI-powered chatbot API for mental health support, enabling users to engage in private conversations with the AI. •Curated m ental health content m odule, providing users with personalized recommendations for books, podcasts, and other resources to support their mental well-being. •Role-based authentication API (RBAC) to manage user roles and permissions securely. •Post & Com m ent API with morph relationships to handle reactions dynamically. •Optim ized API perform ance by improving database queries and implementing caching. Fork & Knife – Restaurant Managem ent System A restaurant management system built with Laravel & MySQL, streamlining order processing, menu management, and customer interactions. •Order Managem ent: Customers can place and track orders in real time. •Role-Based Authentication (RBAC): Secure access for admins, staff, and customers. •Menu & Inventory Managem ent: Allows restaurant owners to add, update, and rem ove menu items. 1 / 2 Job Portal – Com pany-Specific Recruitm ent System A custom job portal designed for a specific company to manage job postings, applications, and hiring processes efficiently. •Job Posting & Managem ent: HR can post, edit, and manage job listings. •Application Tracking: Allows applicants to submit resumes and track application status. •Role-Based Authentication: Secure access for HR, recruiters, and applicants. SKILLS Front End: HTML CSS JS basics Blade Templete Bootstrap Back End: PHP Laravel MySQL Restful API Tools: Git GitHub Postman COURSES Back End developm ent with laravel Naamal initiative10/2024 – 02/2025 •PHP •MySQL •Laravel •Final Project - Jobs Portal CERTIFICATES PHP developm ent: Digital Egypt Pioneers Initiative - DEPI · Internship VOLUNTEER EXPERIENCE CAT Reloaded PHP Backend Circle Supervisor •Mentoring members in PHP, MySQL, and backend developm ent. •Created a Back-End Roadm ap to guide Fresh developers. •Organized technical workshops and provided learning resources. CAT Reloaded Logistics Circle Supervisor •Managed event logistics for workshops and hackathons. •Led a team handling venue arrangem ents and scheduling. LANGUAGES English B1Arabic native 2 / 2'

In [92]:
cleaned_resume2 = clean_resume_text(resume_text)
cleaned_resume2

'ahm ed wael mujahid a7med wael a7medwael10 mansoura egypt profile end developer specializing php laravel mysql passion building scalable secure web applications experienced restful api development database optimization authentication systems eager learn new technologies improve performance education bachelor com puter control system engineering faculty engineering mansoura university2020 2025 professional experience php web developer digital egypt pioneers initiative depi internship04 2024 10 2024 gained hands experience php laravel mysql developing web applications worked backend developm ent database optim ization api integration enhance system enhanced business com unication skills berlitz egypt business english track led development team building backend fork knife restaurant management system projects fadfadly ai powered mental health platform developed backend restful apis laravel mysql implementing custom ai powered chatbot api mental health support enabling users engage private conversations ai curated ental health content odule providing users personalized recommendations books podcasts resources support mental role based authentication api rbac manage user roles permissions securely post com ent api morph relationships handle reactions dynamically optim ized api perform ance improving database queries implementing caching fork knife restaurant managem ent system restaurant management system built laravel mysql streamlining order processing menu management customer interactions order managem ent customers place track orders real time role based authentication rbac secure access admins staff customers menu inventory managem ent allows restaurant owners add update rem ove menu items job portal com pany specific recruitm ent system custom job portal designed specific company manage job postings applications hiring processes efficiently job posting managem ent hr post edit manage job listings application tracking allows applicants submit resumes track application status role based authentication secure access hr recruiters applicants skills end html css js basics blade templete bootstrap end php laravel mysql restful api tools git github postman courses end developm ent laravel naamal initiative10 2024 02 2025 php mysql laravel final project jobs portal certificates php developm ent digital egypt pioneers initiative depi internship volunteer experience cat reloaded php backend circle supervisor mentoring members php mysql backend developm ent created end roadm ap guide fresh developers organized technical workshops provided learning resources cat reloaded logistics circle supervisor managed event logistics workshops hackathons led team handling venue arrangem ents scheduling languages english b1arabic native'

In [93]:
# create pandas dataframe with the cleaned resumes

data = {
    "Resume": [cleaned_resume1, cleaned_resume2],
    "Name": ["Ahmed El-Sayed", "Ahmed Wael Mujahid"]
}
dataframe = pd.DataFrame(data)
dataframe

                                              Resume                Name
0  ahmed el sayed email phone location cairo egyp...      Ahmed El-Sayed
1  ahm ed wael mujahid a7med wael a7medwael10 man...  Ahmed Wael Mujahid

In [95]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
from sentence_transformers import SentenceTransformer

def recommend_candidates(dataframe, job_description, top_k=2):
    """
    Recommend top candidates for a job based on semantic similarity between resumes and job description.
    
    Args:
        dataframe (pd.DataFrame): DataFrame containing candidate resumes with columns 'Name' and 'Resume'
        job_description (str): Text describing the job requirements and responsibilities
        top_k (int): Number of top candidates to recommend (default: 2)
        
    Returns:
        pd.DataFrame: A DataFrame with top candidates ranked by similarity score
    """
    # Load pre-trained sentence embedding model
    model = SentenceTransformer('job_embeddings_model_evaluated2')  # Fast lightweight model
    
    # Clean the job description using the same function used for resumes
    cleaned_job_desc = clean_resume_text(job_description)
    
    # Get embeddings for job description and all resumes
    job_embedding = model.encode([cleaned_job_desc])[0]
    
    # Store similarity scores
    similarities = []
    
    # Calculate similarity for each resume
    for idx, row in dataframe.iterrows():
        resume_text = row['Resume']
        resume_embedding = model.encode([resume_text])[0]
        
        # Calculate cosine similarity
        similarity = cosine_similarity([job_embedding], [resume_embedding])[0][0]
        similarities.append({
            'Name': row['Name'],
            'Similarity': similarity,
            'Resume': resume_text
        })
    
    # Convert to DataFrame and sort by similarity
    results_df = pd.DataFrame(similarities)
    results_df = results_df.sort_values(by='Similarity', ascending=False).reset_index(drop=True)
    
    # Add rank column
    results_df['Rank'] = results_df.index + 1
    
    # Return top_k results
    return results_df.head(top_k)[['Rank', 'Name', 'Similarity', 'Resume']]

In [3]:
job_description ="""
Senior Backend Developer - Enterprise Solutions

About the Role:
We are seeking an experienced Senior Backend Developer to join our growing engineering team. As a Senior Backend Developer, you will be responsible for designing, implementing, and maintaining scalable server-side applications and APIs that power our enterprise SaaS platform. The ideal candidate has extensive experience with modern backend frameworks, database optimization, and cloud infrastructure.

Key Responsibilities:
• Design and develop robust, high-performance backend systems and APIs using modern technologies
• Lead the architecture and implementation of new features and services
• Optimize application performance and ensure high availability of mission-critical systems
• Implement and maintain security best practices to protect sensitive customer data
• Design and maintain database schemas, queries, and stored procedures for efficient data access
• Work with DevOps to establish CI/CD pipelines and ensure smooth deployment processes
• Collaborate with frontend developers to integrate user-facing elements with server-side logic
• Mentor junior developers and provide technical leadership to the backend team
• Participate in code reviews to maintain code quality and share knowledge
• Troubleshoot and debug complex production issues
• Document architecture decisions, APIs, and technical specifications

Required Skills & Experience:
• 5+ years of professional experience in backend development
• Expert knowledge of PHP and at least one major PHP framework (Laravel, Symfony, or similar)
• Strong experience with RESTful API design and implementation
• Proficient with relational databases (MySQL, PostgreSQL) and query optimization
• Experience with caching strategies, message queues, and other performance optimization techniques
• Strong understanding of software design patterns and architecture principles
• Experience with containerization technologies (Docker, Kubernetes)
• Proficient with version control systems, preferably Git
• Knowledge of automated testing methodologies and tools
• Experience with CI/CD pipelines and deployment strategies
• Strong problem-solving skills and attention to detail

Preferred Qualifications:
• Experience with microservices architecture and domain-driven design
• Knowledge of NoSQL databases (MongoDB, Redis)
• Experience with cloud platforms (AWS, Azure, or GCP)
• Familiarity with event-driven architectures and message brokers
• Knowledge of GraphQL API implementation
• Experience with real-time communication protocols (WebSockets)
• Understanding of infrastructure-as-code principles
• Experience with performance monitoring and APM tools"""

In [4]:
import os
import PyPDF2
import pandas as pd

def extract_text_from_pdfs(folder_path):
    
    # Dictionary to store results
    results = {
        'filename': [],
        'text': []
    }
    
    # Get all PDF files in the folder
    pdf_files = [f for f in os.listdir(folder_path) if f.lower().endswith('.pdf')]
    
    # Process each PDF file
    for pdf_file in pdf_files:
        pdf_path = os.path.join(folder_path, pdf_file)

        # Read the PDF
        pdf_reader = PyPDF2.PdfReader(pdf_path)
        
        # Extract text from all pages
        resume_text = ""
        for page in pdf_reader.pages:
            page_text = page.extract_text()
            # Clean up text - remove line breaks and pipes
            page_text = page_text.replace("\n", " ").replace("|", " ")
            resume_text += page_text + " "
            
        # Clean up extra whitespace
        resume_text = " ".join(resume_text.split())
        
        # Store the results
        results['filename'].append(pdf_file)
        results['text'].append(resume_text)
        
        print(f"Successfully extracted text from {pdf_file}")

    
    # Convert results to DataFrame
    df = pd.DataFrame(results)
    return df

In [5]:
folder_path = "cv"
extracted_text =  extract_text_from_pdfs(folder_path)

Successfully extracted text from 1 year of  experience.pdf
Successfully extracted text from 2+ years of experience.pdf
Successfully extracted text from 4+ years of experience.pdf
Successfully extracted text from 5 years of experience.pdf
Successfully extracted text from 6+ years of experience.pdf
Successfully extracted text from Ahmed-Wael-Mujahid-resume.pdf
Successfully extracted text from Ahmed_El-Sayed_CV.pdf

In [6]:
print(extracted_text["text"].iloc[1])

Mona Hassan Email: mona.hassan.dev@example.com Phone: +20 101 234 5678 Location: Cairo, Egypt LinkedIn: linkedin.com/in/mona-hassan GitHub: github.com/monahassan-dev Portfolio: monahassan.dev Professional Summary Backend Developer with 2+ years of experience in Laravel development, API integration, and MySQL optimization. Passionate about writing clean code and learning new technologies. Technical Skills Languages: PHP, JavaScript Frameworks: Laravel, Lumen Databases: MySQL, Redis DevOps: Docker, GitHub Actions Tools: Git, Composer, Postman API: REST, Passport Other: MVC, Caching Work Experience Backend Developer DevSparks - Alexandria, Egypt Jun 2022 - Present - Developed and maintained internal web applications using Laravel 9. - Integrated RESTful APIs and third-party payment gateways. - Collaborated with frontend developers on API design and documentation. Intern Laravel Developer Bright Future Tech - Alexandria, Egypt Mar 2021 - May 2022 - Assisted in Laravel backend tasks, including CRUD operations. - Created and managed database schemas with migrations. Education BSc in Computer Science, Alexandria University, Egypt - 2021 Certifications Laravel Bootcamp Certificate (2022) Projects - Taskly - Task management tool using Laravel and Vue.js - Eventor - Simple event booking platform with admin panel Languages Arabic - Native, English - Intermediate

# actual start

In [8]:
job_description ="""
Senior Backend Developer - Enterprise Solutions

About the Role:
We are seeking an experienced Senior Backend Developer to join our growing engineering team. As a Senior Backend Developer, you will be responsible for designing, implementing, and maintaining scalable server-side applications and APIs that power our enterprise SaaS platform. The ideal candidate has extensive experience with modern backend frameworks, database optimization, and cloud infrastructure.

Key Responsibilities:
• Design and develop robust, high-performance backend systems and APIs using modern technologies
• Lead the architecture and implementation of new features and services
• Optimize application performance and ensure high availability of mission-critical systems
• Implement and maintain security best practices to protect sensitive customer data
• Design and maintain database schemas, queries, and stored procedures for efficient data access
• Work with DevOps to establish CI/CD pipelines and ensure smooth deployment processes
• Collaborate with frontend developers to integrate user-facing elements with server-side logic
• Mentor junior developers and provide technical leadership to the backend team
• Participate in code reviews to maintain code quality and share knowledge
• Troubleshoot and debug complex production issues
• Document architecture decisions, APIs, and technical specifications

Required Skills & Experience:
• 5+ years of professional experience in backend development
• Expert knowledge of PHP and at least one major PHP framework (Laravel, Symfony, or similar)
• Strong experience with RESTful API design and implementation
• Proficient with relational databases (MySQL, PostgreSQL) and query optimization
• Experience with caching strategies, message queues, and other performance optimization techniques
• Strong understanding of software design patterns and architecture principles
• Experience with containerization technologies (Docker, Kubernetes)
• Proficient with version control systems, preferably Git
• Knowledge of automated testing methodologies and tools
• Experience with CI/CD pipelines and deployment strategies
• Strong problem-solving skills and attention to detail

Preferred Qualifications:
• Experience with microservices architecture and domain-driven design
• Knowledge of NoSQL databases (MongoDB, Redis)
• Experience with cloud platforms (AWS, Azure, or GCP)
• Familiarity with event-driven architectures and message brokers
• Knowledge of GraphQL API implementation
• Experience with real-time communication protocols (WebSockets)
• Understanding of infrastructure-as-code principles
• Experience with performance monitoring and APM tools"""

In [9]:
import pandas as pd
import re
import string
import spacy
from spacy.lang.en.stop_words import STOP_WORDS

def clean_resume_text(text):
    """Clean resume text for embedding and recommendation"""
    
    # Load spaCy model
    nlp = spacy.load('en_core_web_sm')
    
    # 1. Convert to lowercase
    text = text.lower()
    
    # 2. Remove contact information
    text = re.sub(r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b', ' ', text)  # Email
    text = re.sub(r'(\+\d{1,3}[-\s]?)?\(?\d{3}\)?[-\s]?\d{3}[-\s]?\d{4}', ' ', text)  # Phone
    
    # 3. Remove URLs and social media handles
    text = re.sub(r'https?://\S+|www\.\S+', ' ', text)
    text = re.sub(r'linkedin\.com\S*|github\.com\S*|twitter\.com\S*', ' ', text)
    
    # 4. Remove locations and addresses
    location_patterns = [
        r'\b[A-Z][a-z]+,\s*[A-Z]{2}\b',  # City, State
        r'\b[A-Z][a-z]+\s+[A-Z]{2}\s+\d{5}\b',  # City State ZIP
    ]
    for pattern in location_patterns:
        text = re.sub(pattern, ' ', text)
    
    # 5. Remove dates (but preserve skill versions like 'Python 3')
    text = re.sub(r'\b(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*\s+\d{4}\b', ' ', text)
    text = re.sub(r'\b\d{1,2}/\d{1,2}/\d{2,4}\b', ' ', text)
    text = re.sub(r'\b\d{4}-\d{2,4}\b', ' ', text)
    
    # 6. Remove special characters but keep important ones for skills
    text = text.replace('|', ' ').replace('•', ' ').replace('–', ' ').replace('/', ' ')
    
    # 7. Process with spaCy for advanced cleaning
    doc = nlp(text)
    
    # 8. Keep only relevant tokens 
    tokens = []
    for token in doc:
        # Skip if token is punctuation, stopword, or just whitespace
        if (
            not token.is_punct
            and not token.is_stop
            and not token.is_space
            and token.text.strip()
            and len(token.text.strip()) > 1
        ):
            # Lemmatize the token
            tokens.append(token.text)
    
    # 9. Join tokens back into cleaned text
    cleaned_text = " ".join(tokens)
    
    # 10. Remove extra whitespace
    cleaned_text = " ".join(cleaned_text.split())
    # return the cleaned_text in the shape of pandas dataframe with each has its own index
    return cleaned_text

In [10]:
def clean_resume_dataframe(df):
    """
    Clean all resume texts in a DataFrame
    
    Args:
        df (pd.DataFrame): DataFrame with 'filename' and 'text' columns containing raw resume texts
        
    Returns:
        pd.DataFrame: DataFrame with original columns plus 'cleaned_text' column
    """
    # Create a copy to avoid modifying the original
    cleaned_df = df.copy()
    
    # Apply cleaning function to each text
    cleaned_df['Resume'] = cleaned_df['text'].apply(clean_resume_text)
    
    print(f"Successfully cleaned {len(cleaned_df)} resume texts")
    
    return cleaned_df

In [11]:
cleaned_resumes = clean_resume_dataframe(extracted_text)

Successfully cleaned 7 resume texts

In [12]:
cleaned_resumes.head()

,filename,text,Resume
0,1 year of experience.pdf,Youssef Nabil Email: youssef.nabil@example.com...,youssef nabil email phone location cairo egypt...
1,2+ years of experience.pdf,Mona Hassan Email: mona.hassan.dev@example.com...,mona hassan email phone location cairo egypt l...
2,4+ years of experience.pdf,Omar Khaled Email: omar.khaled@example.com Pho...,omar khaled email phone location cairo egypt l...
3,5 years of experience.pdf,Hassan Tarek Email: hassan.tarek@example.com P...,hassan tarek email phone location cairo egypt ...
4,6+ years of experience.pdf,Salma Youssef Email: salma.youssef@example.com...,salma youssef email phone location cairo egypt...

In [13]:
cleaned_resumes["Resume"].iloc[1]

'mona hassan email phone location cairo egypt linkedin github portfolio monahassan.dev professional summary backend developer years experience laravel development api integration mysql optimization passionate writing clean code learning new technologies technical skills languages php javascript frameworks laravel lumen databases mysql redis devops docker github actions tools git composer postman api rest passport mvc caching work experience backend developer devsparks alexandria egypt present developed maintained internal web applications laravel integrated restful apis party payment gateways collaborated frontend developers api design documentation intern laravel developer bright future tech alexandria egypt assisted laravel backend tasks including crud operations created managed database schemas migrations education bsc computer science alexandria university egypt 2021 certifications laravel bootcamp certificate 2022 projects taskly task management tool laravel vue.js eventor simple event booking platform admin panel languages arabic native english intermediate'

In [14]:
cleaned_resumes["Resume"].iloc[0]

'youssef nabil email phone location cairo egypt linkedin github portfolio youssefnabil.dev professional summary junior laravel developer year hands experience backend tasks api development eager grow scalable system development technical skills languages php frameworks laravel databases mysql devops github docker basic tools git postman api rest sanctum mvc json apis work experience laravel intern bright future tech cairo egypt present developed basic crud apis laravel 10 participated team standups code reviews wrote api docs assisted debugging education bsc computer science cairo university 2023 certifications laravel fundamentals certificate 2023 projects bloglite simple blogging system laravel devnotes personal note taking app tags languages arabic native english intermediate'

In [25]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
from sentence_transformers import SentenceTransformer

def recommend_candidates(dataframe, job_description, top_k= None):
    
    # Load pre-trained sentence embedding model
    model = SentenceTransformer('job_embeddings_model_evaluated2')  # Fast lightweight model
    
    # Clean the job description using the same function used for resumes
    cleaned_job_desc = clean_resume_text(job_description)
    
    # Get embeddings for job description and all resumes
    job_embedding = model.encode([cleaned_job_desc])[0]
    
    # Store similarity scores
    similarities = []
    
    # Calculate similarity for each resume
    for idx, row in dataframe.iterrows():
        resume_text = row['Resume']
        resume_embedding = model.encode([resume_text])[0]
        
        # Calculate cosine similarity
        similarity = cosine_similarity([job_embedding], [resume_embedding])[0][0]
        similarities.append({
            'Name': row['filename'],
            'Similarity': similarity,
            'Resume': resume_text
        })
    
    # Convert to DataFrame and sort by similarity
    results_df = pd.DataFrame(similarities)
    results_df = results_df.sort_values(by='Similarity', ascending=False).reset_index(drop=True)
    
    # Add rank column
    results_df['Rank'] = results_df.index + 1
    
    # Return top_k results
    return results_df.head(top_k)[['Rank', 'Name', 'Similarity', 'Resume']]

In [26]:
recommend_candidates( cleaned_resumes ,  job_description)

,Rank,Name,Similarity,Resume
0,1,Ahmed_El-Sayed_CV.pdf,0.919801,ahmed el sayed email phone location cairo egyp...
1,2,6+ years of experience.pdf,0.859858,salma youssef email phone location cairo egypt...
2,3,Ahmed-Wael-Mujahid-resume.pdf,0.853325,ahm ed wael mujahid a7med wael a7medwael10 man...
3,4,4+ years of experience.pdf,0.812492,omar khaled email phone location cairo egypt l...
4,5,5 years of experience.pdf,0.789512,hassan tarek email phone location cairo egypt ...
5,6,1 year of experience.pdf,0.684858,youssef nabil email phone location cairo egypt...
6,7,2+ years of experience.pdf,0.631795,mona hassan email phone location cairo egypt l...